#!/bin/bash
set -euo pipefail

echo "=============================================="
echo "            INSTALLER ROUTER UBUNTU           "
echo "=============================================="

# Utility untuk menampilkan daftar interface (selain loopback)
list_interfaces() {
    ip -o link show | awk -F': ' '{print $2}' | grep -v '^lo$'
}

# Validasi / pilih interface; jika default tidak ada dan mode interaktif, minta input user.
select_interface() {
    local role="$1"
    local candidate="$2"

    if [[ -n "$candidate" ]] && ip link show "$candidate" >/dev/null 2>&1; then
        echo "$candidate"
        return
    fi

    if [[ ! -t 0 ]]; then
        echo "Error: interface default '$candidate' untuk $role tidak ditemukan dan tidak ada input interaktif." >&2
        echo "       Set variabel lingkungan ${role}_IF sebelum menjalankan skrip." >&2
        exit 1
    fi

    while true; do
        echo "Interface '$candidate' untuk $role tidak ditemukan."
        echo "Daftar interface yang terdeteksi:"
        list_interfaces | sed 's/^/  - /'
        read -r -p "Masukkan nama interface untuk $role: " candidate
        if [[ -n "$candidate" ]] && ip link show "$candidate" >/dev/null 2>&1; then
            echo "$candidate"
            return
        fi
        echo "Input kosong atau interface tidak valid. Coba lagi."
    done
}

# Pilih file Netplan yang ingin dipakai tanpa memaksa nama baru.
detect_netplan_file() {
    if [[ -n "${NETPLAN_FILE:-}" ]]; then
        echo "$NETPLAN_FILE"
        return
    fi

    local first_existing=""
    if [[ -d /etc/netplan ]]; then
        while IFS= read -r -d '' file; do
            first_existing="$file"
            break
        done < <(find /etc/netplan -maxdepth 1 -type f -name "*.yaml" -print0 2>/dev/null | sort -z)
    fi

    if [[ -n "$first_existing" ]]; then
        echo "$first_existing"
    else
        echo "/etc/netplan/01-ngfw-router.yaml"
    fi
}

DEFAULT_WAN="${WAN_IF:-ens33}"
DEFAULT_LAN="${LAN_IF:-ens37}"

WAN_IF="$(select_interface "WAN" "$DEFAULT_WAN")"
LAN_IF="$(select_interface "LAN" "$DEFAULT_LAN")"
NFQUEUE_NUM="${NFQUEUE_NUM:-0}"
export WAN_IF LAN_IF NFQUEUE_NUM

echo " Menggunakan interface WAN=${WAN_IF} dan LAN=${LAN_IF}"

# --------------------------------------------------------------------
# 1. Konfigurasi Netplan / NetworkManager
# --------------------------------------------------------------------
configure_netplan() {
    local netplan_file
    netplan_file="$(detect_netplan_file)"
    echo " Menggunakan file Netplan: $netplan_file"

    if [[ -f "$netplan_file" ]]; then
        local backup="${netplan_file}.bak.$(date +%Y%m%d%H%M%S)"
        echo "  Membuat backup $backup"
        sudo cp "$netplan_file" "$backup"
    fi

    echo " Menulis konfigurasi Netplan..."
    sudo tee "$netplan_file" >/dev/null <<EOF
# Generated by router.sh
network:
  version: 2
  renderer: NetworkManager

  ethernets:
    $WAN_IF:
      dhcp4: true
      dhcp6: false

    $LAN_IF:
      addresses:
        - 192.168.5.1/24
      dhcp4: false
      dhcp6: false
EOF

    echo " Menerapkan Netplan..."
    sudo netplan apply
    sudo systemctl restart NetworkManager
}

# --------------------------------------------------------------------
# 2. IP Forwarding (sysctl)
# --------------------------------------------------------------------
configure_sysctl() {
    local sysctl_file="/etc/sysctl.d/99-snort-router.conf"
    echo " Mengaktifkan IPv4 forwarding..."
    sudo tee "$sysctl_file" >/dev/null <<'EOF'
# Generated by router.sh
net.ipv4.ip_forward = 1
EOF

    sudo sysctl -w net.ipv4.ip_forward=1 >/dev/null
    sudo sysctl -p "$sysctl_file" >/dev/null
}

# --------------------------------------------------------------------
# 3. Atur iptables (NAT, FORWARD, NFQUEUE)
# --------------------------------------------------------------------
configure_iptables() {
    echo " Mengonfigurasi iptables (NAT/FORWARD)..."
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y iptables-persistent

    sudo iptables -F
    sudo iptables -t nat -F
    sudo iptables -X
    sudo iptables -t nat -X

    sudo iptables -t nat -A POSTROUTING -o "$WAN_IF" -j MASQUERADE

    sudo iptables -I FORWARD 1 -i "$LAN_IF" -o "$WAN_IF" -j NFQUEUE --queue-num "$NFQUEUE_NUM" --queue-bypass
    sudo iptables -I FORWARD 2 -i "$WAN_IF" -o "$LAN_IF" -j NFQUEUE --queue-num "$NFQUEUE_NUM" --queue-bypass

    sudo iptables -A FORWARD -i "$LAN_IF" -o "$WAN_IF" -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
    sudo iptables -A FORWARD -i "$WAN_IF" -o "$LAN_IF" -m state --state ESTABLISHED,RELATED -j ACCEPT

    sudo netfilter-persistent save
}

# --------------------------------------------------------------------
# 4. DHCP Server
# --------------------------------------------------------------------
configure_dhcp() {
    local default_subnet="192.168.5.0"
    local default_netmask="255.255.255.0"
    local default_range_start="192.168.5.2"
    local default_range_end="192.168.5.10"
    local default_gateway="192.168.5.1"
    local default_dns="8.8.8.8"

    read -r -p "Masukkan SUBNET [${default_subnet}]: " subnet
    subnet=${subnet:-$default_subnet}

    read -r -p "Masukkan NETMASK [${default_netmask}]: " netmask
    netmask=${netmask:-$default_netmask}

    read -r -p "Masukkan RANGE START [${default_range_start}]: " range_start
    range_start=${range_start:-$default_range_start}

    read -r -p "Masukkan RANGE END [${default_range_end}]: " range_end
    range_end=${range_end:-$default_range_end}

    read -r -p "Masukkan GATEWAY [${default_gateway}]: " gateway
    gateway=${gateway:-$default_gateway}

    read -r -p "Masukkan DNS Server [${default_dns}]: " dns
    dns=${dns:-$default_dns}

    echo " Menginstal / mengonfigurasi ISC DHCP Server..."
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y isc-dhcp-server

    sudo tee /etc/default/isc-dhcp-server >/dev/null <<EOF
INTERFACESv4="$LAN_IF"
INTERFACESv6=""
EOF

    sudo tee /etc/dhcp/dhcpd.conf >/dev/null <<EOF
# Generated by router.sh
default-lease-time 600;
max-lease-time 7200;

subnet $subnet netmask $netmask {
  range $range_start $range_end;
  option routers $gateway;
  option subnet-mask $netmask;
  option domain-name-servers $dns;
}
EOF

    echo "============================================="
    echo " Subnet    : $subnet/$netmask"
    echo " Range     : $range_start - $range_end"
    echo " Gateway   : $gateway"
    echo " DNS       : $dns"
    echo " LAN IF    : $LAN_IF"
    echo " WAN IF    : $WAN_IF"
    echo "============================================="

    sudo systemctl enable --now isc-dhcp-server
}

# --------------------------------------------------------------------
# Eksekusi tahapan
# --------------------------------------------------------------------
configure_netplan
configure_sysctl
configure_iptables
configure_dhcp

echo " ALL DONE! Your system is now acting as ROUTER "
